# Project Information
site_name: Los Alamos Computational Condensed Matter Summer School 2025
site_url: https://laqmss-trial.github.io/mkdocs

# Mkdocs Theme (Material Mkdocs)
theme:
  name: material
  #custom_dir: overrides
  palette:
    primary: "pink"
    accent: "pink"
  #logo: assets/logo.png
  features:
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - overrides/extra.css

nav:
  - Overview: index.md
  - Apply: apply.md
  - Schedule: schedule.md
  - Lecturers: lecturers.md
  - Lecture Notes: lecture_notes.md
  - Tutorials: tutorials.md
  - Venue/Location: location.md
  - Contact: contact.md
